# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: twitter-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - volume:/var/lib/db/
    environment:
      POSTGRES_PASSWORD: bobolo
      POSTGRES_DB: twitter

  adminer:
    image: adminer
    ports:
      - 8080:8080

  rabbit:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  jupyter:
    build:
      context: .
      dockerfile: ./Jupyter_Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/workspace

volumes:
  volume:
