# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - volume:/var/lib/db/
    environment:
      POSTGRES_PASSWORD: bobolo
      POSTGRES_DB: twitter

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    volume: